# pages/viewer.py
# 3D protein-peptide complex viewer using py3Dmol
#
# Loads data/complex_top20/{pep_id}.pdb - generated by scripts/build_complexes.py
# from the real receptor (docking/receptor_af.pdbqt) + docked peptide poses
# (docking/results/{pep_id}_out.pdbqt). See PROJECT_SUMMARY.md Section 4/5
# for how the receptor and ligands were validated.

import streamlit as st
import streamlit.components.v1 as comp
import os
from utils.paths import (
    DATA_DIR,
    DOCKING_DIR,
    COMPLEX_DIR,
    FOLDED_DIR,
)
try:
    import py3Dmol
    PY3DMOL_AVAILABLE = True
except ImportError:
    PY3DMOL_AVAILABLE = False

from utils.data import load_top_candidates, PEPTIDE_CHAIN, RECEPTOR_CHAIN, PROTEIN_NAME


def render():
    st.markdown('<div class="section-head">3D Structure Viewer</div>',
        unsafe_allow_html=True)

    df = load_top_candidates()

    if len(df) == 0:
        st.warning("No candidates found - run docking first (see data/docking_scores.csv).")
        return

    col_viewer, col_controls = st.columns([2, 1])

    with col_controls:
        pep_id = st.selectbox("Select inhibitor", df["id"].tolist())
        row = df[df["id"] == pep_id].iloc[0]

        style = st.radio("Style", ["Cartoon", "Surface", "Stick"], horizontal=True)
        spin = st.toggle("Auto-rotate")
        surface = st.checkbox("Show pocket surface", True)

        st.markdown("---")
        st.markdown(f"""
        <div style="background:rgba(124,58,237,0.08);border:0.5px solid rgba(124,58,237,0.2);
        border-radius:10px;padding:12px 14px;margin-bottom:8px">
          <div style="font-size:9px;color:#6D6D8A;font-family:monospace;margin-bottom:4px">SEQUENCE</div>
          <div style="font-family:'JetBrains Mono',monospace;font-size:12px;color:#06B6D4;
          letter-spacing:.06em">{row.get("sequence", "N/A")}</div>
        </div>
        <div style="background:rgba(124,58,237,0.08);border:0.5px solid rgba(124,58,237,0.2);
        border-radius:8px;padding:8px 10px">
          <div style="font-size:8px;color:#6D6D8A;font-family:monospace">BINDING ΔG</div>
          <div style="font-size:18px;font-weight:700;color:#A78BFA">{row.get("dG", "N/A")} kcal/mol</div>
        </div>
        """, unsafe_allow_html=True)

    with col_viewer:
        # Use the COMPLEX_DIR constant (from utils.paths) instead of a
        # hardcoded "D:\mdr-pepdesign\..." path - the old hardcoded path
        # only worked on one machine and used unescaped backslashes.
        complex_path = os.path.join(COMPLEX_DIR, f"{pep_id}.pdb")

        if not PY3DMOL_AVAILABLE:
            st.error("py3Dmol is not installed. Run: pip install py3Dmol")
            return

        if not os.path.exists(complex_path):
            st.markdown(f"""
            <div style="width:100%;height:500px;background:var(--card2);
            border-radius:12px;display:flex;align-items:center;justify-content:center;
            border:0.5px solid var(--border2)">
            <div style="text-align:center;color:var(--text3);font-family:monospace;font-size:12px">
              No complex file found for {pep_id}<br><br>
              Run <code style="color:#7C3AED">python scripts/build_complexes.py</code><br>
              to generate <code style="color:#7C3AED">{complex_path}</code>
            </div>
            </div>
            """, unsafe_allow_html=True)
            return

        pdb_str = open(complex_path).read()
        view = py3Dmol.view(width=680, height=500)
        view.addModel(pdb_str, "pdb")

        style_lower = style.lower()

        # Receptor - translucent cartoon, identified by RECEPTOR_CHAIN
        # (explicit chain selector, not "not peptide", so this stays
        # correct even if the complex file ever has more than 2 chains)
        view.setStyle(
            {"chain": RECEPTOR_CHAIN},
            {"cartoon": {"color": "#8AAABF", "opacity": 0.75}}
        )

        # Peptide inhibitor
        if style_lower == "cartoon":
            view.setStyle({"chain": PEPTIDE_CHAIN}, {"cartoon": {"color": "#E85D24", "opacity": 1.0}})
        elif style_lower == "surface":
            view.setStyle({"chain": PEPTIDE_CHAIN}, {"sphere": {"colorscheme": "orangeCarbon", "radius": 0.8}})
        else:
            view.setStyle({"chain": PEPTIDE_CHAIN}, {"stick": {"colorscheme": "orangeCarbon", "radius": 0.3}})

        view.addStyle({"chain": PEPTIDE_CHAIN}, {"stick": {"colorscheme": "orangeCarbon", "radius": 0.25}})

        # Pocket surface - shown on the receptor only
        if surface:
            view.addSurface(
                py3Dmol.VDW,
                {"opacity": 0.18, "color": "white"},
                {"chain": RECEPTOR_CHAIN}
            )

        view.zoomTo({"chain": PEPTIDE_CHAIN})
        view.setBackgroundColor("#050B18")
        if spin:
            view.spin(True)

        # _make_html() is the correct call for non-notebook contexts like
        # Streamlit. py3Dmol's _repr_html_() requires an active IPython/
        # Jupyter kernel and raises ImportError outside one - confirmed
        # by testing both directly against this real complex file.
        html = view._make_html()
        comp.html(html, height=520)